// Mock data para desarrollo de Knordica
// Reemplazar con datos reales de Supabase en producción.
// Datos representativos de propiedades en Mérida, Venezuela.

import type { Zone, Agent, PropertyCard, PropertyImage } from "@/types/property";

// ─── ZONAS ─────────────────────────────────────────────────
export const MOCK_ZONES: Zone[] = [
  {
    id: "zone-1",
    slug: "la-pedregosa",
    name_es: "La Pedregosa",
    name_en: "Pedregosa Alta",
    description_es:
      "Una de las zonas residenciales más consolidadas de Mérida, con vistas privilegiadas a la ciudad y cercanía al campus universitario.",
    description_en:
      "One of Mérida's most established residential areas, with privileged city views and proximity to the university campus.",
    city: "Mérida",
    lat: 8.596,
    lng: -71.14,
    cover_image_url: null,
    featured: true,
  },
  {
    id: "zone-2",
    slug: "la-floresta",
    name_es: "La Floresta",
    name_en: "La Floresta",
    description_es:
      "Tranquilo sector residencial con amplias avenidas arborizadas y una comunidad consolidada de familias.",
    description_en:
      "A tranquil residential area with wide tree-lined avenues and an established family community.",
    city: "Mérida",
    lat: 8.605,
    lng: -71.152,
    cover_image_url: null,
    featured: true,
  },
  {
    id: "zone-3",
    slug: "las-tapias",
    name_es: "Las Tapias",
    name_en: "Las Tapias",
    description_es:
      "Zona en crecimiento con inversión activa. Preferida por jóvenes profesionales e inversores que buscan oportunidades de plusvalía.",
    description_en:
      "A growing area with active investment. Preferred by young professionals and investors seeking appreciation opportunities.",
    city: "Mérida",
    lat: 8.612,
    lng: -71.16,
    cover_image_url: null,
    featured: false,
  },
  {
    id: "zone-4",
    slug: "el-encanto",
    name_es: "El Encanto",
    name_en: "La Hechicera heights",
    description_es:
      "Zona residencial en las alturas de Mérida, con clima fresco y vistas panorámicas excepcionales.",
    description_en:
      "A residential area in the heights of Mérida, with cool weather and exceptional panoramic views.",
    city: "Mérida",
    lat: 8.58,
    lng: -71.125,
    cover_image_url: null,
    featured: true,
  },
  {
    id: "zone-5",
    slug: "belensate",
    name_es: "Belensate",
    name_en: "Belensate",
    description_es:
      "Sector tradicional y bien comunicado, con oferta variada de casas y apartamentos a precios accesibles.",
    description_en:
      "A traditional, well-connected area with a varied range of houses and apartments at accessible prices.",
    city: "Mérida",
    lat: 8.618,
    lng: -71.144,
    cover_image_url: null,
    featured: false,
  },
];

// ─── AGENTES ────────────────────────────────────────────────
export const MOCK_AGENTS: Agent[] = [
  {
    id: "agent-1",
    full_name: "Carlos Valera",
    email: "carlos@knordica.com",
    phone: "+58 412 242 3334",
    whatsapp: "5804122423334",
    bio_es:
      "Especialista en propiedades residenciales seleccionadas. 10 años en el mercado inmobiliario de Mérida, Venezuela.",
    bio_en:
      "Specialist in selected residential properties. 10 years in the Mérida, Venezuela real estate market.",
    avatar_url: null,
    role: "senior",
    active: true,
  },
  {
    id: "agent-2",
    full_name: "María Fernanda Rodríguez",
    email: "mariafe@knordica.com",
    phone: "+58 424 111 2222",
    whatsapp: "5804241112222",
    bio_es:
      "Especializada en inversión y propiedades comerciales. MBA con enfoque en mercados emergentes.",
    bio_en:
      "Specialized in investment and commercial properties. MBA with a focus on emerging markets.",
    avatar_url: null,
    role: "agent",
    active: true,
  },
];

// ─── PROPIEDADES ────────────────────────────────────────────
export const MOCK_PROPERTIES: (PropertyCard & { images?: PropertyImage[] })[] = [
  {
    id: "prop-1",
    slug: "casa-moderna-la-pedregosa-4hab",
    operation: "venta",
    property_type: "casa",
    status: "activa",
    featured: true,
    exclusive: true,
    new_listing: false,
    price_reduced: false,
    price: 280000,
    price_currency: "USD",
    area_total: 520,
    area_built: 380,
    bedrooms: 4,
    bathrooms: 4,
    parking_spaces: 3,
    zone: MOCK_ZONES[0],
    title: "Casa moderna en La Pedregosa con vistas a la ciudad",
    short_description:
      "Residencia contemporánea de 4 habitaciones en suite. Acabados contemporáneos, jardín privado y vistas panorámicas privilegiadas.",
    cover_image: {
      id: "prop-1-cover",
      property_id: "prop-1",
      url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
      alt_es: "Casa moderna en La Pedregosa con vistas a la ciudad",
      alt_en: "Modern house in La Pedregosa with city views",
      sort_order: 0,
      is_cover: true,
    },
    images: [
      {
        id: "prop-1-img1",
        property_id: "prop-1",
        url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Fachada de la casa moderna",
        alt_en: "Modern house facade",
        sort_order: 0,
        is_cover: true,
      },
      {
        id: "prop-1-img2",
        property_id: "prop-1",
        url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Cocina y área social de concepto abierto",
        alt_en: "Open concept kitchen and social area",
        sort_order: 1,
        is_cover: false,
      },
      {
        id: "prop-1-img3",
        property_id: "prop-1",
        url: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Habitación principal espaciosa",
        alt_en: "Spacious master bedroom",
        sort_order: 2,
        is_cover: false,
      },
      {
        id: "prop-1-img4",
        property_id: "prop-1",
        url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Baño moderno con finos acabados",
        alt_en: "Modern bathroom with refined finishes",
        sort_order: 3,
        is_cover: false,
      }
    ],
  },
  {
    id: "prop-2",
    slug: "apartamento-la-floresta-3hab",
    operation: "venta",
    property_type: "apartamento",
    status: "activa",
    featured: true,
    exclusive: false,
    new_listing: true,
    price_reduced: false,
    price: 145000,
    price_currency: "USD",
    area_total: 210,
    area_built: 185,
    bedrooms: 3,
    bathrooms: 2,
    parking_spaces: 2,
    zone: MOCK_ZONES[1],
    title: "Apartamento de 3 habitaciones en La Floresta",
    short_description:
      "Piso 8, zona tranquila y residencial. Balcón con vista a las montañas. Conjunto cerrado con seguridad.",
    cover_image: {
      id: "prop-2-cover",
      property_id: "prop-2",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80",
      alt_es: "Apartamento de 3 habitaciones en La Floresta",
      alt_en: "3 bedroom apartment in La Floresta",
      sort_order: 0,
      is_cover: true,
    },
    images: [
      {
        id: "prop-2-img1",
        property_id: "prop-2",
        url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Sala de estar e iluminación natural",
        alt_en: "Living room with natural lighting",
        sort_order: 0,
        is_cover: true,
      },
      {
        id: "prop-2-img2",
        property_id: "prop-2",
        url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Habitación principal moderna",
        alt_en: "Modern master bedroom",
        sort_order: 1,
        is_cover: false,
      },
      {
        id: "prop-2-img3",
        property_id: "prop-2",
        url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Cocina equipada",
        alt_en: "Equipped kitchen",
        sort_order: 2,
        is_cover: false,
      }
    ],
  },
  {
    id: "prop-3",
    slug: "casa-campo-el-encanto-5hab",
    operation: "venta",
    property_type: "casa",
    status: "activa",
    featured: true,
    exclusive: true,
    new_listing: false,
    price_reduced: false,
    price: 420000,
    price_currency: "USD",
    area_total: 1200,
    area_built: 680,
    bedrooms: 5,
    bathrooms: 6,
    parking_spaces: 4,
    zone: MOCK_ZONES[3],
    title: "Casa de campo en El Encanto con piscina y terreno",
    short_description:
      "Propiedad seleccionada a 1.800 msnm. Clima fresco, piscina climatizada, jardines formales y guest house independiente.",
    cover_image: {
      id: "prop-3-cover",
      property_id: "prop-3",
      url: "https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=1200&q=80",
      alt_es: "Casa de campo en El Encanto con piscina y terreno",
      alt_en: "Country house in El Encanto with pool and land",
      sort_order: 0,
      is_cover: true,
    },
    images: [
      {
        id: "prop-3-img1",
        property_id: "prop-3",
        url: "https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Vista exterior de la casa de campo",
        alt_en: "Exterior view of the country house",
        sort_order: 0,
        is_cover: true,
      },
      {
        id: "prop-3-img2",
        property_id: "prop-3",
        url: "https://images.unsplash.com/photo-1542718610-a1d656d1884c?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Interior de madera con chimenea",
        alt_en: "Wooden interior with fireplace",
        sort_order: 1,
        is_cover: false,
      },
      {
        id: "prop-3-img3",
        property_id: "prop-3",
        url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Entorno natural y montañas",
        alt_en: "Natural surroundings and mountains",
        sort_order: 2,
        is_cover: false,
      }
    ],
  },
  {
    id: "prop-4",
    slug: "apartamento-ejecutivo-la-pedregosa",
    operation: "alquiler",
    property_type: "apartamento",
    status: "activa",
    featured: false,
    exclusive: false,
    new_listing: true,
    price_reduced: false,
    price: 1200,
    price_currency: "USD",
    area_total: 145,
    area_built: 130,
    bedrooms: 2,
    bathrooms: 2,
    parking_spaces: 1,
    zone: MOCK_ZONES[0],
    title: "Apartamento ejecutivo en La Pedregosa",
    short_description:
      "Ideal para ejecutivos y profesionales. Totalmente amoblado y equipado. Acceso a gimnasio y área social.",
    cover_image: {
      id: "prop-4-cover",
      property_id: "prop-4",
      url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80",
      alt_es: "Apartamento ejecutivo en La Pedregosa",
      alt_en: "Executive apartment in La Pedregosa",
      sort_order: 0,
      is_cover: true,
    },
    images: [
      {
        id: "prop-4-img1",
        property_id: "prop-4",
        url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Vista interna del apartamento amoblado",
        alt_en: "Interior view of the furnished apartment",
        sort_order: 0,
        is_cover: true,
      },
      {
        id: "prop-4-img2",
        property_id: "prop-4",
        url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Sala comedor",
        alt_en: "Dining and living area",
        sort_order: 1,
        is_cover: false,
      },
      {
        id: "prop-4-img3",
        property_id: "prop-4",
        url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Dormitorio contemporáneo",
        alt_en: "Contemporary bedroom",
        sort_order: 2,
        is_cover: false,
      }
    ],
  },
  {
    id: "prop-5",
    slug: "local-comercial-belensate-180m2",
    operation: "venta",
    property_type: "local",
    status: "activa",
    featured: false,
    exclusive: false,
    new_listing: false,
    price_reduced: true,
    price: 95000,
    price_currency: "USD",
    area_total: 180,
    area_built: 180,
    bedrooms: null,
    bathrooms: 2,
    parking_spaces: 2,
    zone: MOCK_ZONES[4],
    title: "Local comercial en Belensate — Alta visibilidad",
    short_description:
      "Local en esquina con frente doble. Techo alto, 4 baños, depósito independiente. Excelente para clínica, galería o tienda.",
    cover_image: {
      id: "prop-5-cover",
      property_id: "prop-5",
      url: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80",
      alt_es: "Local comercial en Belensate — Alta visibilidad",
      alt_en: "Commercial local in Belensate — High visibility",
      sort_order: 0,
      is_cover: true,
    },
    images: [
      {
        id: "prop-5-img1",
        property_id: "prop-5",
        url: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Espacio de oficina/comercio",
        alt_en: "Office/commercial space",
        sort_order: 0,
        is_cover: true,
      },
      {
        id: "prop-5-img2",
        property_id: "prop-5",
        url: "https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Interior amplio y luminoso",
        alt_en: "Spacious and bright interior",
        sort_order: 1,
        is_cover: false,
      }
    ],
  },
  {
    id: "prop-6",
    slug: "terreno-urbanizado-las-tapias",
    operation: "venta",
    property_type: "terreno",
    status: "activa",
    featured: false,
    exclusive: false,
    new_listing: false,
    price_reduced: false,
    price: 72000,
    price_currency: "USD",
    area_total: 800,
    area_built: null,
    bedrooms: null,
    bathrooms: null,
    parking_spaces: null,
    zone: MOCK_ZONES[2],
    title: "Terreno urbanizado en Las Tapias",
    short_description:
      "Lote de 800m² con todos los servicios. Topografía plana. Zona de alto crecimiento. Ideal para desarrollo de 6-8 unidades.",
    cover_image: {
      id: "prop-6-cover",
      property_id: "prop-6",
      url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80",
      alt_es: "Terreno urbanizado en Las Tapias",
      alt_en: "Urbanized land in Las Tapias",
      sort_order: 0,
      is_cover: true,
    },
    images: [
      {
        id: "prop-6-img1",
        property_id: "prop-6",
        url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Vista general del terreno plano",
        alt_en: "General view of the flat land",
        sort_order: 0,
        is_cover: true,
      },
      {
        id: "prop-6-img2",
        property_id: "prop-6",
        url: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Paisaje circundante",
        alt_en: "Surrounding landscape",
        sort_order: 1,
        is_cover: false,
      }
    ],
  },
  {
    id: "prop-7",
    slug: "casa-la-floresta-3hab-alquiler",
    operation: "alquiler",
    property_type: "casa",
    status: "activa",
    featured: false,
    exclusive: false,
    new_listing: false,
    price_reduced: false,
    price: 900,
    price_currency: "USD",
    area_total: 280,
    area_built: 240,
    bedrooms: 3,
    bathrooms: 3,
    parking_spaces: 2,
    zone: MOCK_ZONES[1],
    title: "Casa en La Floresta para alquilar",
    short_description:
      "Casa familiar en urbanización cerrada con vigilancia 24h. Jardín privado, cuarto de servicio y zona de lavandería.",
    cover_image: {
      id: "prop-7-cover",
      property_id: "prop-7",
      url: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80",
      alt_es: "Casa en La Floresta para alquilar",
      alt_en: "House in La Floresta for rent",
      sort_order: 0,
      is_cover: true,
    },
    images: [
      {
        id: "prop-7-img1",
        property_id: "prop-7",
        url: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Fachada principal e ingreso de garaje",
        alt_en: "Main facade and garage entry",
        sort_order: 0,
        is_cover: true,
      },
      {
        id: "prop-7-img2",
        property_id: "prop-7",
        url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Área social interna",
        alt_en: "Internal social area",
        sort_order: 1,
        is_cover: false,
      }
    ],
  },
  {
    id: "prop-8",
    slug: "penthouse-la-pedregosa",
    operation: "venta",
    property_type: "apartamento",
    status: "activa",
    featured: true,
    exclusive: true,
    new_listing: true,
    price_reduced: false,
    price: 340000,
    price_currency: "USD",
    area_total: 320,
    area_built: 280,
    bedrooms: 4,
    bathrooms: 3,
    parking_spaces: 3,
    zone: MOCK_ZONES[0],
    title: "Penthouse de 320m² en La Pedregosa — Último piso",
    short_description:
      "Terraza privada de 180m² con vista 360°. Acabados importados seleccionados. Única unidad disponible.",
    cover_image: {
      id: "prop-8-cover",
      property_id: "prop-8",
      url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
      alt_es: "Penthouse de 320m² en La Pedregosa — Último piso",
      alt_en: "320sqm Penthouse in La Pedregosa — Top floor",
      sort_order: 0,
      is_cover: true,
    },
    images: [
      {
        id: "prop-8-img1",
        property_id: "prop-8",
        url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Terraza exterior con piscina del penthouse",
        alt_en: "Exterior penthouse terrace with pool",
        sort_order: 0,
        is_cover: true,
      },
      {
        id: "prop-8-img2",
        property_id: "prop-8",
        url: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Diseño exterior de noche",
        alt_en: "Night exterior design",
        sort_order: 1,
        is_cover: false,
      },
      {
        id: "prop-8-img3",
        property_id: "prop-8",
        url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Habitación con balcón",
        alt_en: "Room with balcony",
        sort_order: 2,
        is_cover: false,
      }
    ],
  },
];

// ─── ESTADÍSTICAS PARA HERO ─────────────────────────────────
export const SITE_STATS = {
  propiedades: 47,
  zonas: 12,
  operaciones: 183,
  satisfaccion: 98,
};

// ─── TESTIMONIOS ────────────────────────────────────────────
export const MOCK_TESTIMONIALS = [
  {
    id: "t1",
    author_name: "Alejandro Mora",
    author_title: "Comprador — La Pedregosa",
    quote_es:
      "El proceso fue completamente diferente a todo lo que había vivido antes en Mérida. Claridad total, sin sorpresas, y encontraron exactamente lo que buscaba.",
    quote_en:
      "The process was completely different from anything I'd experienced before in Mérida. Total clarity, no surprises, and they found exactly what I was looking for.",
    rating: 5,
  },
  {
    id: "t2",
    author_name: "Valentina Torres",
    author_title: "Inversora — Las Tapias",
    quote_es:
      "Knordica entiende el mercado local a un nivel que ninguna otra firma aquí tiene. Su análisis fue lo que me convenció de invertir en Las Tapias.",
    quote_en:
      "Knordica understands the local market at a level no other firm here has. Their analysis was what convinced me to invest in Las Tapias.",
    rating: 5,
  },
  {
    id: "t3",
    author_name: "Roberto Sánchez",
    author_title: "Vendedor — El Encanto",
    quote_es:
      "Vendí en 6 semanas. La presentación digital que hicieron de mi propiedad fue de otro nivel. Todo en USD, sin complicaciones.",
    quote_en:
      "Sold in 6 weeks. The digital presentation they made of my property was on another level. Everything in USD, no complications.",
    rating: 5,
  },
];
