// Mock data para desarrollo de Knordica
// Reemplazar con datos reales de Supabase en producción.
// Datos representativos de propiedades en Mérida, Venezuela.

import type { Zone, Agent, PropertyCard, PropertyImage } from "@/types/property";

// ─── ZONAS ─────────────────────────────────────────────────
export const MOCK_ZONES: Zone[] = [
  {
    id: "zone-1",
    slug: "la-pedregosa",
    name_es: "La Pedregosa",
    name_en: "Pedregosa Alta",
    description_es:
      "Una de las zonas residenciales más consolidadas de Mérida, con vistas privilegiadas a la ciudad y cercanía al campus universitario.",
    description_en:
      "One of Mérida's most established residential areas, with privileged city views and proximity to the university campus.",
    city: "Mérida",
    lat: 8.596,
    lng: -71.14,
    cover_image_url: null,
    featured: true,
  },
  {
    id: "zone-2",
    slug: "la-floresta",
    name_es: "La Floresta",
    name_en: "La Floresta",
    description_es:
      "Tranquilo sector residencial con amplias avenidas arborizadas y una comunidad consolidada de familias.",
    description_en:
      "A tranquil residential area with wide tree-lined avenues and an established family community.",
    city: "Mérida",
    lat: 8.605,
    lng: -71.152,
    cover_image_url: null,
    featured: true,
  },
  {
    id: "zone-3",
    slug: "las-tapias",
    name_es: "Las Tapias",
    name_en: "Las Tapias",
    description_es:
      "Zona en crecimiento con inversión activa. Preferida por jóvenes profesionales e inversores que buscan oportunidades de plusvalía.",
    description_en:
      "A growing area with active investment. Preferred by young professionals and investors seeking appreciation opportunities.",
    city: "Mérida",
    lat: 8.612,
    lng: -71.16,
    cover_image_url: null,
    featured: false,
  },
  {
    id: "zone-4",
    slug: "el-encanto",
    name_es: "El Encanto",
    name_en: "La Hechicera heights",
    description_es:
      "Zona residencial en las alturas de Mérida, con clima fresco y vistas panorámicas excepcionales.",
    description_en:
      "A residential area in the heights of Mérida, with cool weather and exceptional panoramic views.",
    city: "Mérida",
    lat: 8.58,
    lng: -71.125,
    cover_image_url: null,
    featured: true,
  },
    {
    id: "zone-5",
    slug: "belensate",
    name_es: "Belensate",
    name_en: "Belensate",
    description_es: "Sector tradicional y bien comunicado, con oferta variada de casas y apartamentos a precios accesibles.",
    description_en: "A traditional, well-connected area with a varied range of houses and apartments at accessible prices.",
    city: "Mérida",
    lat: 8.618,
    lng: -71.144,
    cover_image_url: null,
    featured: true,
  },
  {
    id: "zone-6",
    slug: "el-arenal",
    name_es: "El Arenal",
    name_en: "El Arenal",
    description_es: "Sector de rápido crecimiento comercial y residencial, ideal para desarrollos nuevos.",
    description_en: "Fast growing commercial and residential sector, ideal for new developments.",
    city: "Mérida",
    lat: 8.585,
    lng: -71.115,
    cover_image_url: null,
    featured: true,
  },
  {
    id: "zone-7",
    slug: "los-chorros",
    name_es: "Los Chorros",
    name_en: "Los Chorros",
    description_es: "Zona rodeada de naturaleza y clima andino de montaña, muy fresca y cotizada.",
    description_en: "Area surrounded by nature and Andean mountain climate, very cool and sought-after.",
    city: "Mérida",
    lat: 8.625,
    lng: -71.135,
    cover_image_url: null,
    featured: true,
  },
  {
    id: "zone-8",
    slug: "mucuchies",
    name_es: "Mucuchíes",
    name_en: "Mucuchíes",
    description_es: "Pueblo típico andino de páramo a gran altitud, clima frío y arquitectura colonial.",
    description_en: "Typical high-altitude Andean paramo town, cold weather and colonial architecture.",
    city: "Páramo",
    lat: 8.746,
    lng: -70.92,
    cover_image_url: null,
    featured: true,
  },
  {
    id: "zone-9",
    slug: "el-vigia",
    name_es: "El Vigía",
    name_en: "El Vigía",
    description_es: "Segunda ciudad del estado, importante centro comercial e industrial con clima cálido.",
    description_en: "Second city of the state, important commercial and industrial center with warm climate.",
    city: "El Vigía",
    lat: 8.622,
    lng: -71.643,
    cover_image_url: null,
    featured: true,
  },
  {
    id: "zone-10",
    slug: "centro-historico",
    name_es: "Centro Histórico",
    name_en: "Historical Center",
    description_es: "Corazón cultural de Mérida con arquitectura colonial, museos, iglesias y comercios tradicionales.",
    description_en: "Cultural heart of Mérida with colonial architecture, museums, churches, and traditional shops.",
    city: "Mérida",
    lat: 8.598,
    lng: -71.144,
    cover_image_url: null,
    featured: true,
  },
  {
    id: "zone-11",
    slug: "ejido",
    name_es: "Ejido",
    name_en: "Ejido",
    description_es: "Zona residencial e industrial conectada al trolebús de Mérida, con excelente vialidad.",
    description_en: "Residential and industrial area connected to Mérida's trolleybus, with excellent roads.",
    city: "Ejido",
    lat: 8.547,
    lng: -71.242,
    cover_image_url: null,
    featured: true,
  }
];


// ─── AGENTES ────────────────────────────────────────────────
export const MOCK_AGENTS: Agent[] = [
  {
    id: "agent-1",
    full_name: "Carlos Valera",
    email: "carlos@knordica.com",
    phone: "+58 412 242 3334",
    whatsapp: "5804122423334",
    bio_es:
      "Especialista en propiedades residenciales seleccionadas. 10 años en el mercado inmobiliario de Mérida, Venezuela.",
    bio_en:
      "Specialist in selected residential properties. 10 years in the Mérida, Venezuela real estate market.",
    avatar_url: null,
    role: "senior",
    active: true,
  },
  {
    id: "agent-2",
    full_name: "María Fernanda Rodríguez",
    email: "mariafe@knordica.com",
    phone: "+58 424 111 2222",
    whatsapp: "5804241112222",
    bio_es:
      "Especializada en inversión y propiedades comerciales. MBA con enfoque en mercados emergentes.",
    bio_en:
      "Specialized in investment and commercial properties. MBA with a focus on emerging markets.",
    avatar_url: null,
    role: "agent",
    active: true,
  },
];

// ─── PROPIEDADES ────────────────────────────────────────────
export const MOCK_PROPERTIES: (PropertyCard & { images?: PropertyImage[] })[] = [
  {
    id: "prop-1",
    slug: "casa-moderna-la-pedregosa-4hab",
    operation: "venta",
    property_type: "casa",
    status: "activa",
    featured: true,
    exclusive: true,
    new_listing: false,
    price_reduced: false,
    price: 280000,
    price_currency: "USD",
    area_total: 520,
    area_built: 380,
    bedrooms: 4,
    bathrooms: 4,
    parking_spaces: 3,
    zone: MOCK_ZONES[0],
    title: "Casa moderna en La Pedregosa con vistas a la ciudad",
    short_description:
      "Residencia contemporánea de 4 habitaciones en suite. Acabados contemporáneos, jardín privado y vistas panorámicas privilegiadas.",
    cover_image: {
      id: "prop-1-cover",
      property_id: "prop-1",
      url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
      alt_es: "Casa moderna en La Pedregosa con vistas a la ciudad",
      alt_en: "Modern house in La Pedregosa with city views",
      sort_order: 0,
      is_cover: true,
    },
    images: [
      {
        id: "prop-1-img1",
        property_id: "prop-1",
        url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Fachada de la casa moderna",
        alt_en: "Modern house facade",
        sort_order: 0,
        is_cover: true,
      },
      {
        id: "prop-1-img2",
        property_id: "prop-1",
        url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Cocina y área social de concepto abierto",
        alt_en: "Open concept kitchen and social area",
        sort_order: 1,
        is_cover: false,
      },
      {
        id: "prop-1-img3",
        property_id: "prop-1",
        url: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Habitación principal espaciosa",
        alt_en: "Spacious master bedroom",
        sort_order: 2,
        is_cover: false,
      },
      {
        id: "prop-1-img4",
        property_id: "prop-1",
        url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Baño moderno con finos acabados",
        alt_en: "Modern bathroom with refined finishes",
        sort_order: 3,
        is_cover: false,
      }
    ],
  },
  {
    id: "prop-2",
    slug: "apartamento-la-floresta-3hab",
    operation: "venta",
    property_type: "apartamento",
    status: "activa",
    featured: true,
    exclusive: false,
    new_listing: true,
    price_reduced: false,
    price: 145000,
    price_currency: "USD",
    area_total: 210,
    area_built: 185,
    bedrooms: 3,
    bathrooms: 2,
    parking_spaces: 2,
    zone: MOCK_ZONES[1],
    title: "Apartamento de 3 habitaciones en La Floresta",
    short_description:
      "Piso 8, zona tranquila y residencial. Balcón con vista a las montañas. Conjunto cerrado con seguridad.",
    cover_image: {
      id: "prop-2-cover",
      property_id: "prop-2",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80",
      alt_es: "Apartamento de 3 habitaciones en La Floresta",
      alt_en: "3 bedroom apartment in La Floresta",
      sort_order: 0,
      is_cover: true,
    },
    images: [
      {
        id: "prop-2-img1",
        property_id: "prop-2",
        url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Sala de estar e iluminación natural",
        alt_en: "Living room with natural lighting",
        sort_order: 0,
        is_cover: true,
      },
      {
        id: "prop-2-img2",
        property_id: "prop-2",
        url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Habitación principal moderna",
        alt_en: "Modern master bedroom",
        sort_order: 1,
        is_cover: false,
      },
      {
        id: "prop-2-img3",
        property_id: "prop-2",
        url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Cocina equipada",
        alt_en: "Equipped kitchen",
        sort_order: 2,
        is_cover: false,
      }
    ],
  },
  {
    id: "prop-3",
    slug: "casa-campo-el-encanto-5hab",
    operation: "vacacional",
    property_type: "casa",
    status: "activa",
    featured: true,
    exclusive: true,
    new_listing: false,
    price_reduced: false,
    price: 420000,
    price_currency: "USD",
    area_total: 1200,
    area_built: 680,
    bedrooms: 5,
    bathrooms: 6,
    parking_spaces: 4,
    zone: MOCK_ZONES[3],
    title: "Casa de campo en El Encanto con piscina y terreno",
    short_description:
      "Propiedad seleccionada a 1.800 msnm. Clima fresco, piscina climatizada, jardines formales y guest house independiente.",
    cover_image: {
      id: "prop-3-cover",
      property_id: "prop-3",
      url: "https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=1200&q=80",
      alt_es: "Casa de campo en El Encanto con piscina y terreno",
      alt_en: "Country house in El Encanto with pool and land",
      sort_order: 0,
      is_cover: true,
    },
    images: [
      {
        id: "prop-3-img1",
        property_id: "prop-3",
        url: "https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Vista exterior de la casa de campo",
        alt_en: "Exterior view of the country house",
        sort_order: 0,
        is_cover: true,
      },
      {
        id: "prop-3-img2",
        property_id: "prop-3",
        url: "https://images.unsplash.com/photo-1542718610-a1d656d1884c?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Interior de madera con chimenea",
        alt_en: "Wooden interior with fireplace",
        sort_order: 1,
        is_cover: false,
      },
      {
        id: "prop-3-img3",
        property_id: "prop-3",
        url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Entorno natural y montañas",
        alt_en: "Natural surroundings and mountains",
        sort_order: 2,
        is_cover: false,
      }
    ],
  },
  {
    id: "prop-4",
    slug: "apartamento-ejecutivo-la-pedregosa",
    operation: "alquiler",
    property_type: "apartamento",
    status: "activa",
    featured: false,
    exclusive: false,
    new_listing: true,
    price_reduced: false,
    price: 1200,
    price_currency: "USD",
    area_total: 145,
    area_built: 130,
    bedrooms: 2,
    bathrooms: 2,
    parking_spaces: 1,
    zone: MOCK_ZONES[0],
    title: "Apartamento ejecutivo en La Pedregosa",
    short_description:
      "Ideal para ejecutivos y profesionales. Totalmente amoblado y equipado. Acceso a gimnasio y área social.",
    cover_image: {
      id: "prop-4-cover",
      property_id: "prop-4",
      url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80",
      alt_es: "Apartamento ejecutivo en La Pedregosa",
      alt_en: "Executive apartment in La Pedregosa",
      sort_order: 0,
      is_cover: true,
    },
    images: [
      {
        id: "prop-4-img1",
        property_id: "prop-4",
        url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Vista interna del apartamento amoblado",
        alt_en: "Interior view of the furnished apartment",
        sort_order: 0,
        is_cover: true,
      },
      {
        id: "prop-4-img2",
        property_id: "prop-4",
        url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Sala comedor",
        alt_en: "Dining and living area",
        sort_order: 1,
        is_cover: false,
      },
      {
        id: "prop-4-img3",
        property_id: "prop-4",
        url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Dormitorio contemporáneo",
        alt_en: "Contemporary bedroom",
        sort_order: 2,
        is_cover: false,
      }
    ],
  },
  {
    id: "prop-5",
    slug: "local-comercial-belensate-180m2",
    operation: "venta",
    property_type: "local",
    status: "activa",
    featured: false,
    exclusive: false,
    new_listing: false,
    price_reduced: true,
    price: 95000,
    price_currency: "USD",
    area_total: 180,
    area_built: 180,
    bedrooms: null,
    bathrooms: 2,
    parking_spaces: 2,
    zone: MOCK_ZONES[4],
    title: "Local comercial en Belensate — Alta visibilidad",
    short_description:
      "Local en esquina con frente doble. Techo alto, 4 baños, depósito independiente. Excelente para clínica, galería o tienda.",
    cover_image: {
      id: "prop-5-cover",
      property_id: "prop-5",
      url: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80",
      alt_es: "Local comercial en Belensate — Alta visibilidad",
      alt_en: "Commercial local in Belensate — High visibility",
      sort_order: 0,
      is_cover: true,
    },
    images: [
      {
        id: "prop-5-img1",
        property_id: "prop-5",
        url: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Espacio de oficina/comercio",
        alt_en: "Office/commercial space",
        sort_order: 0,
        is_cover: true,
      },
      {
        id: "prop-5-img2",
        property_id: "prop-5",
        url: "https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Interior amplio y luminoso",
        alt_en: "Spacious and bright interior",
        sort_order: 1,
        is_cover: false,
      }
    ],
  },
  {
    id: "prop-6",
    slug: "terreno-urbanizado-las-tapias",
    operation: "venta",
    property_type: "terreno",
    status: "activa",
    featured: false,
    exclusive: false,
    new_listing: false,
    price_reduced: false,
    price: 72000,
    price_currency: "USD",
    area_total: 800,
    area_built: null,
    bedrooms: null,
    bathrooms: null,
    parking_spaces: null,
    zone: MOCK_ZONES[2],
    title: "Terreno urbanizado en Las Tapias",
    short_description:
      "Lote de 800m² con todos los servicios. Topografía plana. Zona de alto crecimiento. Ideal para desarrollo de 6-8 unidades.",
    cover_image: {
      id: "prop-6-cover",
      property_id: "prop-6",
      url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80",
      alt_es: "Terreno urbanizado en Las Tapias",
      alt_en: "Urbanized land in Las Tapias",
      sort_order: 0,
      is_cover: true,
    },
    images: [
      {
        id: "prop-6-img1",
        property_id: "prop-6",
        url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Vista general del terreno plano",
        alt_en: "General view of the flat land",
        sort_order: 0,
        is_cover: true,
      },
      {
        id: "prop-6-img2",
        property_id: "prop-6",
        url: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Paisaje circundante",
        alt_en: "Surrounding landscape",
        sort_order: 1,
        is_cover: false,
      }
    ],
  },
  {
    id: "prop-7",
    slug: "casa-la-floresta-3hab-alquiler",
    operation: "alquiler",
    property_type: "casa",
    status: "activa",
    featured: false,
    exclusive: false,
    new_listing: false,
    price_reduced: false,
    price: 900,
    price_currency: "USD",
    area_total: 280,
    area_built: 240,
    bedrooms: 3,
    bathrooms: 3,
    parking_spaces: 2,
    zone: MOCK_ZONES[1],
    title: "Casa en La Floresta para alquilar",
    short_description:
      "Casa familiar en urbanización cerrada con vigilancia 24h. Jardín privado, cuarto de servicio y zona de lavandería.",
    cover_image: {
      id: "prop-7-cover",
      property_id: "prop-7",
      url: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80",
      alt_es: "Casa en La Floresta para alquilar",
      alt_en: "House in La Floresta for rent",
      sort_order: 0,
      is_cover: true,
    },
    images: [
      {
        id: "prop-7-img1",
        property_id: "prop-7",
        url: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Fachada principal e ingreso de garaje",
        alt_en: "Main facade and garage entry",
        sort_order: 0,
        is_cover: true,
      },
      {
        id: "prop-7-img2",
        property_id: "prop-7",
        url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Área social interna",
        alt_en: "Internal social area",
        sort_order: 1,
        is_cover: false,
      }
    ],
  },
  {
    id: "prop-8",
    slug: "penthouse-la-pedregosa",
    operation: "venta",
    property_type: "apartamento",
    status: "activa",
    featured: true,
    exclusive: true,
    new_listing: true,
    price_reduced: false,
    price: 340000,
    price_currency: "USD",
    area_total: 320,
    area_built: 280,
    bedrooms: 4,
    bathrooms: 3,
    parking_spaces: 3,
    zone: MOCK_ZONES[0],
    title: "Penthouse de 320m² en La Pedregosa — Último piso",
    short_description:
      "Terraza privada de 180m² con vista 360°. Acabados importados seleccionados. Única unidad disponible.",
    cover_image: {
      id: "prop-8-cover",
      property_id: "prop-8",
      url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
      alt_es: "Penthouse de 320m² en La Pedregosa — Último piso",
      alt_en: "320sqm Penthouse in La Pedregosa — Top floor",
      sort_order: 0,
      is_cover: true,
    },
    images: [
      {
        id: "prop-8-img1",
        property_id: "prop-8",
        url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Terraza exterior con piscina del penthouse",
        alt_en: "Exterior penthouse terrace with pool",
        sort_order: 0,
        is_cover: true,
      },
      {
        id: "prop-8-img2",
        property_id: "prop-8",
        url: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Diseño exterior de noche",
        alt_en: "Night exterior design",
        sort_order: 1,
        is_cover: false,
      },
      {
        id: "prop-8-img3",
        property_id: "prop-8",
        url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Habitación con balcón",
        alt_en: "Room with balcony",
        sort_order: 2,
        is_cover: false,
      }
    ],
  },
  {
    id: "prop-9",
    slug: "chalet-montana-mucuchies-3hab",
    operation: "vacacional",
    property_type: "casa",
    status: "activa",
    featured: true,
    exclusive: true,
    new_listing: true,
    price_reduced: false,
    price: 160000,
    price_currency: "USD",
    area_total: 850,
    area_built: 220,
    bedrooms: 3,
    bathrooms: 2,
    parking_spaces: 2,
    zone: MOCK_ZONES[3],
    title: "Chalet de montaña de estilo rústico en Mucuchíes",
    short_description: "Encantadora cabaña de piedra y madera con espectaculares vistas a los picos de Mérida. Chimenea funcional y amplios terrenos.",
    cover_image: {
      id: "prop-9-cover",
      property_id: "prop-9",
      url: "https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=1200&q=80",
      alt_es: "Chalet de montaña de estilo rústico en Mucuchíes",
      alt_en: "Chalet de montaña de estilo rústico en Mucuchíes",
      sort_order: 0,
      is_cover: true,
    },
    images: [
      {
        id: "prop-9-img1",
        property_id: "prop-9",
        url: "https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Chalet de montaña de estilo rústico en Mucuchíes",
        alt_en: "Chalet de montaña de estilo rústico en Mucuchíes",
        sort_order: 0,
        is_cover: true,
      },
      {
        id: "prop-9-img2",
        property_id: "prop-9",
        url: "https://images.unsplash.com/photo-1542718610-a1d656d1884c?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Chalet de montaña de estilo rústico en Mucuchíes",
        alt_en: "Chalet de montaña de estilo rústico en Mucuchíes",
        sort_order: 1,
        is_cover: false,
      },
      {
        id: "prop-9-img3",
        property_id: "prop-9",
        url: "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Chalet de montaña de estilo rústico en Mucuchíes",
        alt_en: "Chalet de montaña de estilo rústico en Mucuchíes",
        sort_order: 2,
        is_cover: false,
      }
    ],
  },
  {
    id: "prop-10",
    slug: "apartamento-terraza-los-chorros",
    operation: "vacacional",
    property_type: "apartamento",
    status: "activa",
    featured: false,
    exclusive: false,
    new_listing: true,
    price_reduced: false,
    price: 110000,
    price_currency: "USD",
    area_total: 140,
    area_built: 125,
    bedrooms: 2,
    bathrooms: 2,
    parking_spaces: 2,
    zone: MOCK_ZONES[0],
    title: "Apartamento moderno con terraza en Los Chorros",
    short_description: "Exclusivo apartamento en planta baja con jardín-terraza privado, acabados de primera y excelente clima de montaña.",
    cover_image: {
      id: "prop-10-cover",
      property_id: "prop-10",
      url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80",
      alt_es: "Apartamento moderno con terraza en Los Chorros",
      alt_en: "Apartamento moderno con terraza en Los Chorros",
      sort_order: 0,
      is_cover: true,
    },
    images: [
      {
        id: "prop-10-img1",
        property_id: "prop-10",
        url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Apartamento moderno con terraza en Los Chorros",
        alt_en: "Apartamento moderno con terraza en Los Chorros",
        sort_order: 0,
        is_cover: true,
      },
      {
        id: "prop-10-img2",
        property_id: "prop-10",
        url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Apartamento moderno con terraza en Los Chorros",
        alt_en: "Apartamento moderno con terraza en Los Chorros",
        sort_order: 1,
        is_cover: false,
      },
      {
        id: "prop-10-img3",
        property_id: "prop-10",
        url: "https://images.unsplash.com/photo-1469022563428-aa04fef9f5a2?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Apartamento moderno con terraza en Los Chorros",
        alt_en: "Apartamento moderno con terraza en Los Chorros",
        sort_order: 2,
        is_cover: false,
      }
    ],
  },
  {
    id: "prop-11",
    slug: "townhouse-lujo-pedregosa-alta",
    operation: "venta",
    property_type: "townhouse",
    status: "activa",
    featured: true,
    exclusive: false,
    new_listing: false,
    price_reduced: false,
    price: 240000,
    price_currency: "USD",
    area_total: 310,
    area_built: 280,
    bedrooms: 4,
    bathrooms: 3,
    parking_spaces: 3,
    zone: MOCK_ZONES[0],
    title: "Townhouse de lujo a estrenar en La Pedregosa Alta",
    short_description: "Arquitectura contemporánea con ventanales de doble altura, cocina de diseñador italiana y terraza con vista a la cordillera.",
    cover_image: {
      id: "prop-11-cover",
      property_id: "prop-11",
      url: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80",
      alt_es: "Townhouse de lujo a estrenar en La Pedregosa Alta",
      alt_en: "Townhouse de lujo a estrenar en La Pedregosa Alta",
      sort_order: 0,
      is_cover: true,
    },
    images: [
      {
        id: "prop-11-img1",
        property_id: "prop-11",
        url: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Townhouse de lujo a estrenar en La Pedregosa Alta",
        alt_en: "Townhouse de lujo a estrenar en La Pedregosa Alta",
        sort_order: 0,
        is_cover: true,
      },
      {
        id: "prop-11-img2",
        property_id: "prop-11",
        url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Townhouse de lujo a estrenar en La Pedregosa Alta",
        alt_en: "Townhouse de lujo a estrenar en La Pedregosa Alta",
        sort_order: 1,
        is_cover: false,
      },
      {
        id: "prop-11-img3",
        property_id: "prop-11",
        url: "https://images.unsplash.com/photo-1600566752355-35792bedcfea?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Townhouse de lujo a estrenar en La Pedregosa Alta",
        alt_en: "Townhouse de lujo a estrenar en La Pedregosa Alta",
        sort_order: 2,
        is_cover: false,
      }
    ],
  },
  {
    id: "prop-12",
    slug: "local-comercial-avenida-las-americas",
    operation: "alquiler",
    property_type: "local",
    status: "activa",
    featured: true,
    exclusive: true,
    new_listing: true,
    price_reduced: false,
    price: 1200,
    price_currency: "USD",
    area_total: 110,
    area_built: 110,
    bedrooms: 0,
    bathrooms: 2,
    parking_spaces: 2,
    zone: MOCK_ZONES[2],
    title: "Excelente local comercial en Avenida Las Américas",
    short_description: "Local en esquina con gran visibilidad y alto tráfico peatonal/vehicular. Perfecto para franquicias, tienda o cafetería.",
    cover_image: {
      id: "prop-12-cover",
      property_id: "prop-12",
      url: "https://images.unsplash.com/photo-1554469384-e58fac16e23a?auto=format&fit=crop&w=1200&q=80",
      alt_es: "Excelente local comercial en Avenida Las Américas",
      alt_en: "Excelente local comercial en Avenida Las Américas",
      sort_order: 0,
      is_cover: true,
    },
    images: [
      {
        id: "prop-12-img1",
        property_id: "prop-12",
        url: "https://images.unsplash.com/photo-1554469384-e58fac16e23a?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Excelente local comercial en Avenida Las Américas",
        alt_en: "Excelente local comercial en Avenida Las Américas",
        sort_order: 0,
        is_cover: true,
      },
      {
        id: "prop-12-img2",
        property_id: "prop-12",
        url: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Excelente local comercial en Avenida Las Américas",
        alt_en: "Excelente local comercial en Avenida Las Américas",
        sort_order: 1,
        is_cover: false,
      }
    ],
  },
  {
    id: "prop-13",
    slug: "casa-residencial-el-vigia-3hab",
    operation: "venta",
    property_type: "casa",
    status: "activa",
    featured: false,
    exclusive: false,
    new_listing: false,
    price_reduced: true,
    price: 95000,
    price_currency: "USD",
    area_total: 300,
    area_built: 180,
    bedrooms: 3,
    bathrooms: 2,
    parking_spaces: 2,
    zone: MOCK_ZONES[4],
    title: "Casa quinta acogedora en zona residencial tranquila",
    short_description: "Casa de una sola planta con porche español, amplio patio posterior cubierto de grama y estacionamiento techado.",
    cover_image: {
      id: "prop-13-cover",
      property_id: "prop-13",
      url: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80",
      alt_es: "Casa quinta acogedora en zona residencial tranquila",
      alt_en: "Casa quinta acogedora en zona residencial tranquila",
      sort_order: 0,
      is_cover: true,
    },
    images: [
      {
        id: "prop-13-img1",
        property_id: "prop-13",
        url: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Casa quinta acogedora en zona residencial tranquila",
        alt_en: "Casa quinta acogedora en zona residencial tranquila",
        sort_order: 0,
        is_cover: true,
      },
      {
        id: "prop-13-img2",
        property_id: "prop-13",
        url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Casa quinta acogedora en zona residencial tranquila",
        alt_en: "Casa quinta acogedora en zona residencial tranquila",
        sort_order: 1,
        is_cover: false,
      }
    ],
  },
  {
    id: "prop-14",
    slug: "apartamento-centro-historico-2hab",
    operation: "alquiler",
    property_type: "habitacion",
    status: "activa",
    featured: false,
    exclusive: false,
    new_listing: false,
    price_reduced: false,
    price: 75000,
    price_currency: "USD",
    area_total: 88,
    area_built: 88,
    bedrooms: 2,
    bathrooms: 1,
    parking_spaces: 1,
    zone: MOCK_ZONES[4],
    title: "Apartamento reformado cerca del Centro Histórico",
    short_description: "Excelente oportunidad para vivir en el centro. Recientemente remodelado, cocina empotrada y cercanía a la plaza Bolívar.",
    cover_image: {
      id: "prop-14-cover",
      property_id: "prop-14",
      url: "https://images.unsplash.com/photo-1502672023488-70e25813eb80?auto=format&fit=crop&w=1200&q=80",
      alt_es: "Apartamento reformado cerca del Centro Histórico",
      alt_en: "Apartamento reformado cerca del Centro Histórico",
      sort_order: 0,
      is_cover: true,
    },
    images: [
      {
        id: "prop-14-img1",
        property_id: "prop-14",
        url: "https://images.unsplash.com/photo-1502672023488-70e25813eb80?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Apartamento reformado cerca del Centro Histórico",
        alt_en: "Apartamento reformado cerca del Centro Histórico",
        sort_order: 0,
        is_cover: true,
      },
      {
        id: "prop-14-img2",
        property_id: "prop-14",
        url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Apartamento reformado cerca del Centro Histórico",
        alt_en: "Apartamento reformado cerca del Centro Histórico",
        sort_order: 1,
        is_cover: false,
      }
    ],
  },
  {
    id: "prop-15",
    slug: "terreno-ejido-con-servicios",
    operation: "venta",
    property_type: "terreno",
    status: "activa",
    featured: false,
    exclusive: false,
    new_listing: true,
    price_reduced: false,
    price: 45000,
    price_currency: "USD",
    area_total: 620,
    area_built: 0,
    bedrooms: 0,
    bathrooms: 0,
    parking_spaces: 0,
    zone: MOCK_ZONES[2],
    title: "Terreno plano completamente urbanizado en Ejido",
    short_description: "Lote plano listo para construir. Cuenta con todas las conexiones de agua, electricidad, y viabilidad de acceso aprobada.",
    cover_image: {
      id: "prop-15-cover",
      property_id: "prop-15",
      url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80",
      alt_es: "Terreno plano completamente urbanizado en Ejido",
      alt_en: "Terreno plano completamente urbanizado en Ejido",
      sort_order: 0,
      is_cover: true,
    },
    images: [
      {
        id: "prop-15-img1",
        property_id: "prop-15",
        url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Terreno plano completamente urbanizado en Ejido",
        alt_en: "Terreno plano completamente urbanizado en Ejido",
        sort_order: 0,
        is_cover: true,
      }
    ],
  },
  {
    id: "prop-16",
    slug: "finca-campestre-tabay-drone",
    operation: "vacacional",
    property_type: "finca",
    status: "activa",
    featured: true,
    exclusive: true,
    new_listing: false,
    price_reduced: false,
    price: 350000,
    price_currency: "USD",
    area_total: 4500,
    area_built: 420,
    bedrooms: 5,
    bathrooms: 4,
    parking_spaces: 5,
    zone: MOCK_ZONES[3],
    title: "Finca campestre productiva en Tabay con casa de campo",
    short_description: "Hermosa propiedad rodeada de naturaleza con arroyos propios, casa principal de estilo colonial, establos y huerto frutal.",
    cover_image: {
      id: "prop-16-cover",
      property_id: "prop-16",
      url: "https://images.unsplash.com/photo-1500076656116-558758c991c1?auto=format&fit=crop&w=1200&q=80",
      alt_es: "Finca campestre productiva en Tabay con casa de campo",
      alt_en: "Finca campestre productiva en Tabay con casa de campo",
      sort_order: 0,
      is_cover: true,
    },
    images: [
      {
        id: "prop-16-img1",
        property_id: "prop-16",
        url: "https://images.unsplash.com/photo-1500076656116-558758c991c1?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Finca campestre productiva en Tabay con casa de campo",
        alt_en: "Finca campestre productiva en Tabay con casa de campo",
        sort_order: 0,
        is_cover: true,
      },
      {
        id: "prop-16-img2",
        property_id: "prop-16",
        url: "https://images.unsplash.com/photo-1473448912268-2022ce9509d8?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Finca campestre productiva en Tabay con casa de campo",
        alt_en: "Finca campestre productiva en Tabay con casa de campo",
        sort_order: 1,
        is_cover: false,
      }
    ],
  },
  {
    id: "prop-17",
    slug: "penthouse-duplex-belensate-exclusivo",
    operation: "venta",
    property_type: "apartamento",
    status: "activa",
    featured: true,
    exclusive: true,
    new_listing: true,
    price_reduced: false,
    price: 450000,
    price_currency: "USD",
    area_total: 420,
    area_built: 390,
    bedrooms: 5,
    bathrooms: 5,
    parking_spaces: 4,
    zone: MOCK_ZONES[4],
    title: "Penthouse duplex de súper lujo en Belensate",
    short_description: "Excepcional penthouse con terraza de 360 grados, ascensor privado directo, acabados de mármol y climatización inteligente.",
    cover_image: {
      id: "prop-17-cover",
      property_id: "prop-17",
      url: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=80",
      alt_es: "Penthouse duplex de súper lujo en Belensate",
      alt_en: "Penthouse duplex de súper lujo en Belensate",
      sort_order: 0,
      is_cover: true,
    },
    images: [
      {
        id: "prop-17-img1",
        property_id: "prop-17",
        url: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Penthouse duplex de súper lujo en Belensate",
        alt_en: "Penthouse duplex de súper lujo en Belensate",
        sort_order: 0,
        is_cover: true,
      },
      {
        id: "prop-17-img2",
        property_id: "prop-17",
        url: "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Penthouse duplex de súper lujo en Belensate",
        alt_en: "Penthouse duplex de súper lujo en Belensate",
        sort_order: 1,
        is_cover: false,
      }
    ],
  },
  {
    id: "prop-18",
    slug: "casa-colonial-centro-merida",
    operation: "vacacional",
    property_type: "habitacion",
    status: "activa",
    featured: false,
    exclusive: false,
    new_listing: false,
    price_reduced: false,
    price: 180000,
    price_currency: "USD",
    area_total: 480,
    area_built: 380,
    bedrooms: 6,
    bathrooms: 3,
    parking_spaces: 1,
    zone: MOCK_ZONES[4],
    title: "Casa colonial restaurada en el Centro de Mérida",
    short_description: "Auténtica casa con patio central de arcos, tejas originales y amplios salones ideales para galería, posada u oficinas.",
    cover_image: {
      id: "prop-18-cover",
      property_id: "prop-18",
      url: "https://images.unsplash.com/photo-1544984243-ec57ea16fe25?auto=format&fit=crop&w=1200&q=80",
      alt_es: "Casa colonial restaurada en el Centro de Mérida",
      alt_en: "Casa colonial restaurada en el Centro de Mérida",
      sort_order: 0,
      is_cover: true,
    },
    images: [
      {
        id: "prop-18-img1",
        property_id: "prop-18",
        url: "https://images.unsplash.com/photo-1544984243-ec57ea16fe25?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Casa colonial restaurada en el Centro de Mérida",
        alt_en: "Casa colonial restaurada en el Centro de Mérida",
        sort_order: 0,
        is_cover: true,
      }
    ],
  },
  {
    id: "prop-19",
    slug: "local-oficinas-centro-profesional",
    operation: "alquiler",
    property_type: "oficina",
    status: "activa",
    featured: false,
    exclusive: false,
    new_listing: false,
    price_reduced: false,
    price: 450,
    price_currency: "USD",
    area_total: 75,
    area_built: 75,
    bedrooms: 0,
    bathrooms: 1,
    parking_spaces: 1,
    zone: MOCK_ZONES[2],
    title: "Oficina corporativa en Centro Profesional prestigioso",
    short_description: "Espacio dividido en tres cubículos, recepción amplia y vista panorámica. Seguridad las 24 horas y estacionamiento público.",
    cover_image: {
      id: "prop-19-cover",
      property_id: "prop-19",
      url: "https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1200&q=80",
      alt_es: "Oficina corporativa en Centro Profesional prestigioso",
      alt_en: "Oficina corporativa en Centro Profesional prestigioso",
      sort_order: 0,
      is_cover: true,
    },
    images: [
      {
        id: "prop-19-img1",
        property_id: "prop-19",
        url: "https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Oficina corporativa en Centro Profesional prestigioso",
        alt_en: "Oficina corporativa en Centro Profesional prestigioso",
        sort_order: 0,
        is_cover: true,
      }
    ],
  },
  {
    id: "prop-20",
    slug: "apartamento-familiar-las-tapias-3hab",
    operation: "venta",
    property_type: "apartamento",
    status: "activa",
    featured: false,
    exclusive: false,
    new_listing: false,
    price_reduced: true,
    price: 120000,
    price_currency: "USD",
    area_total: 165,
    area_built: 165,
    bedrooms: 3,
    bathrooms: 2,
    parking_spaces: 2,
    zone: MOCK_ZONES[2],
    title: "Apartamento familiar espacioso en Las Tapias",
    short_description: "Luminoso apartamento con excelente distribución, cocina empotrada de granito, áreas verdes comunes e ideal para familias.",
    cover_image: {
      id: "prop-20-cover",
      property_id: "prop-20",
      url: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80",
      alt_es: "Apartamento familiar espacioso en Las Tapias",
      alt_en: "Apartamento familiar espacioso en Las Tapias",
      sort_order: 0,
      is_cover: true,
    },
    images: [
      {
        id: "prop-20-img1",
        property_id: "prop-20",
        url: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Apartamento familiar espacioso en Las Tapias",
        alt_en: "Apartamento familiar espacioso en Las Tapias",
        sort_order: 0,
        is_cover: true,
      }
    ],
  },
  {
    id: "prop-21",
    slug: "townhouse-carmenes-estrenar",
    operation: "venta",
    property_type: "townhouse",
    status: "activa",
    featured: false,
    exclusive: false,
    new_listing: true,
    price_reduced: false,
    price: 190000,
    price_currency: "USD",
    area_total: 220,
    area_built: 195,
    bedrooms: 3,
    bathrooms: 3,
    parking_spaces: 2,
    zone: MOCK_ZONES[1],
    title: "Townhouse a estrenar en conjunto privado exclusivo",
    short_description: "Hermosa propiedad con acabados minimalistas, patio interno con parrillera de acero y vigilancia de primer orden.",
    cover_image: {
      id: "prop-21-cover",
      property_id: "prop-21",
      url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
      alt_es: "Townhouse a estrenar en conjunto privado exclusivo",
      alt_en: "Townhouse a estrenar en conjunto privado exclusivo",
      sort_order: 0,
      is_cover: true,
    },
    images: [
      {
        id: "prop-21-img1",
        property_id: "prop-21",
        url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Townhouse a estrenar en conjunto privado exclusivo",
        alt_en: "Townhouse a estrenar en conjunto privado exclusivo",
        sort_order: 0,
        is_cover: true,
      }
    ],
  },
  {
    id: "prop-22",
    slug: "chalet-alpino-san-rafael-tabay",
    operation: "vacacional",
    property_type: "casa",
    status: "activa",
    featured: true,
    exclusive: false,
    new_listing: false,
    price_reduced: false,
    price: 135000,
    price_currency: "USD",
    area_total: 980,
    area_built: 180,
    bedrooms: 3,
    bathrooms: 2,
    parking_spaces: 4,
    zone: MOCK_ZONES[3],
    title: "Chalet estilo alpino en San Rafael de Tabay",
    short_description: "Clima privilegiado, techos altos de madera machihembrada, amplios jardines frutales y terraza exterior para contemplar la niebla.",
    cover_image: {
      id: "prop-22-cover",
      property_id: "prop-22",
      url: "https://images.unsplash.com/photo-1542718610-a1d656d1884c?auto=format&fit=crop&w=1200&q=80",
      alt_es: "Chalet estilo alpino en San Rafael de Tabay",
      alt_en: "Chalet estilo alpino en San Rafael de Tabay",
      sort_order: 0,
      is_cover: true,
    },
    images: [
      {
        id: "prop-22-img1",
        property_id: "prop-22",
        url: "https://images.unsplash.com/photo-1542718610-a1d656d1884c?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Chalet estilo alpino en San Rafael de Tabay",
        alt_en: "Chalet estilo alpino en San Rafael de Tabay",
        sort_order: 0,
        is_cover: true,
      }
    ],
  },
  {
    id: "prop-23",
    slug: "casa-minimalista-hechicera",
    operation: "venta",
    property_type: "casa",
    status: "activa",
    featured: true,
    exclusive: true,
    new_listing: true,
    price_reduced: false,
    price: 320000,
    price_currency: "USD",
    area_total: 680,
    area_built: 410,
    bedrooms: 4,
    bathrooms: 5,
    parking_spaces: 3,
    zone: MOCK_ZONES[3],
    title: "Casa de autor minimalista en La Hechicera",
    short_description: "Líneas rectas, concreto expuesto, domótica completa, jacuzzi climatizado al aire libre y espectaculares vistas del valle.",
    cover_image: {
      id: "prop-23-cover",
      property_id: "prop-23",
      url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80",
      alt_es: "Casa de autor minimalista en La Hechicera",
      alt_en: "Casa de autor minimalista en La Hechicera",
      sort_order: 0,
      is_cover: true,
    },
    images: [
      {
        id: "prop-23-img1",
        property_id: "prop-23",
        url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Casa de autor minimalista en La Hechicera",
        alt_en: "Casa de autor minimalista en La Hechicera",
        sort_order: 0,
        is_cover: true,
      }
    ],
  },
  {
    id: "prop-24",
    slug: "apartamento-estudio-campo-oro",
    operation: "alquiler",
    property_type: "habitacion",
    status: "activa",
    featured: false,
    exclusive: false,
    new_listing: false,
    price_reduced: false,
    price: 250,
    price_currency: "USD",
    area_total: 45,
    area_built: 45,
    bedrooms: 1,
    bathrooms: 1,
    parking_spaces: 1,
    zone: MOCK_ZONES[1],
    title: "Apartamento tipo estudio ideal para estudiantes u oficina",
    short_description: "Ubicado estratégicamente cerca de las facultades universitarias, completamente amueblado y con servicios incluidos.",
    cover_image: {
      id: "prop-24-cover",
      property_id: "prop-24",
      url: "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?auto=format&fit=crop&w=1200&q=80",
      alt_es: "Apartamento tipo estudio ideal para estudiantes u oficina",
      alt_en: "Apartamento tipo estudio ideal para estudiantes u oficina",
      sort_order: 0,
      is_cover: true,
    },
    images: [
      {
        id: "prop-24-img1",
        property_id: "prop-24",
        url: "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Apartamento tipo estudio ideal para estudiantes u oficina",
        alt_en: "Apartamento tipo estudio ideal para estudiantes u oficina",
        sort_order: 0,
        is_cover: true,
      }
    ],
  },
  {
    id: "prop-25",
    slug: "terreno-comercial-terminal-merida",
    operation: "venta",
    property_type: "terreno",
    status: "activa",
    featured: false,
    exclusive: false,
    new_listing: false,
    price_reduced: false,
    price: 220000,
    price_currency: "USD",
    area_total: 1800,
    area_built: 0,
    bedrooms: 0,
    bathrooms: 0,
    parking_spaces: 0,
    zone: MOCK_ZONES[2],
    title: "Terreno comercial de alto potencial frente al terminal",
    short_description: "Lote comercial ideal para construir hotel, centro comercial o galpón de distribución. Doble acceso vial pavimentado.",
    cover_image: {
      id: "prop-25-cover",
      property_id: "prop-25",
      url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80",
      alt_es: "Terreno comercial de alto potencial frente al terminal",
      alt_en: "Terreno comercial de alto potencial frente al terminal",
      sort_order: 0,
      is_cover: true,
    },
    images: [
      {
        id: "prop-25-img1",
        property_id: "prop-25",
        url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Terreno comercial de alto potencial frente al terminal",
        alt_en: "Terreno comercial de alto potencial frente al terminal",
        sort_order: 0,
        is_cover: true,
      }
    ],
  },
  {
    id: "prop-26",
    slug: "casa-quinta-alto-chama",
    operation: "alquiler",
    property_type: "casa",
    status: "activa",
    featured: false,
    exclusive: false,
    new_listing: false,
    price_reduced: true,
    price: 600,
    price_currency: "USD",
    area_total: 450,
    area_built: 320,
    bedrooms: 4,
    bathrooms: 3,
    parking_spaces: 2,
    zone: MOCK_ZONES[2],
    title: "Hermosa casa quinta tradicional en Alto Chama",
    short_description: "Casa clásica andina con acabados de caoba, amplio salón con bar empotrado, terraza y parrillera en zona segura.",
    cover_image: {
      id: "prop-26-cover",
      property_id: "prop-26",
      url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
      alt_es: "Hermosa casa quinta tradicional en Alto Chama",
      alt_en: "Hermosa casa quinta tradicional en Alto Chama",
      sort_order: 0,
      is_cover: true,
    },
    images: [
      {
        id: "prop-26-img1",
        property_id: "prop-26",
        url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Hermosa casa quinta tradicional en Alto Chama",
        alt_en: "Hermosa casa quinta tradicional en Alto Chama",
        sort_order: 0,
        is_cover: true,
      }
    ],
  },
  {
    id: "prop-27",
    slug: "local-restaurante-zona-gastronomica",
    operation: "alquiler",
    property_type: "local",
    status: "activa",
    featured: true,
    exclusive: false,
    new_listing: true,
    price_reduced: false,
    price: 2200,
    price_currency: "USD",
    area_total: 280,
    area_built: 280,
    bedrooms: 0,
    bathrooms: 4,
    parking_spaces: 4,
    zone: MOCK_ZONES[0],
    title: "Local equipado para restaurante en zona gourmet",
    short_description: "Cuenta con área de mesas interna y externa en deck, barra de licores construida, cocina semi-equipada y ductería de aire.",
    cover_image: {
      id: "prop-27-cover",
      property_id: "prop-27",
      url: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80",
      alt_es: "Local equipado para restaurante en zona gourmet",
      alt_en: "Local equipado para restaurante en zona gourmet",
      sort_order: 0,
      is_cover: true,
    },
    images: [
      {
        id: "prop-27-img1",
        property_id: "prop-27",
        url: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Local equipado para restaurante en zona gourmet",
        alt_en: "Local equipado para restaurante en zona gourmet",
        sort_order: 0,
        is_cover: true,
      }
    ],
  },
  {
    id: "prop-28",
    slug: "apartamento-vista-teleferico",
    operation: "alquiler",
    property_type: "apartamento",
    status: "activa",
    featured: true,
    exclusive: false,
    new_listing: false,
    price_reduced: false,
    price: 500,
    price_currency: "USD",
    area_total: 185,
    area_built: 185,
    bedrooms: 3,
    bathrooms: 3,
    parking_spaces: 2,
    zone: MOCK_ZONES[4],
    title: "Apartamento con vista panorámica del Teleférico",
    short_description: "Vistas directas al pico Bolívar y Sierra Nevada. Ascensor privado, acabados de madera fina y cocina de concepto moderno.",
    cover_image: {
      id: "prop-28-cover",
      property_id: "prop-28",
      url: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=80",
      alt_es: "Apartamento con vista panorámica del Teleférico",
      alt_en: "Apartamento con vista panorámica del Teleférico",
      sort_order: 0,
      is_cover: true,
    },
    images: [
      {
        id: "prop-28-img1",
        property_id: "prop-28",
        url: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Apartamento con vista panorámica del Teleférico",
        alt_en: "Apartamento con vista panorámica del Teleférico",
        sort_order: 0,
        is_cover: true,
      }
    ],
  },
  {
    id: "prop-29",
    slug: "townhouse-campestre-ejido",
    operation: "venta",
    property_type: "townhouse",
    status: "activa",
    featured: false,
    exclusive: false,
    new_listing: false,
    price_reduced: false,
    price: 115000,
    price_currency: "USD",
    area_total: 180,
    area_built: 155,
    bedrooms: 3,
    bathrooms: 2,
    parking_spaces: 2,
    zone: MOCK_ZONES[2],
    title: "Townhouse campestre moderno a minutos de Mérida",
    short_description: "Ubicado en conjunto cerrado de Ejido, excelente clima templado, patio de esparcimiento privado y parque infantil.",
    cover_image: {
      id: "prop-29-cover",
      property_id: "prop-29",
      url: "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?auto=format&fit=crop&w=1200&q=80",
      alt_es: "Townhouse campestre moderno a minutos de Mérida",
      alt_en: "Townhouse campestre moderno a minutos de Mérida",
      sort_order: 0,
      is_cover: true,
    },
    images: [
      {
        id: "prop-29-img1",
        property_id: "prop-29",
        url: "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Townhouse campestre moderno a minutos de Mérida",
        alt_en: "Townhouse campestre moderno a minutos de Mérida",
        sort_order: 0,
        is_cover: true,
      }
    ],
  },
  {
    id: "prop-30",
    slug: "mansion-exclusiva-la-mara",
    operation: "vacacional",
    property_type: "casa",
    status: "activa",
    featured: true,
    exclusive: true,
    new_listing: false,
    price_reduced: false,
    price: 450,
    price_currency: "USD",
    area_total: 2500,
    area_built: 850,
    bedrooms: 6,
    bathrooms: 7,
    parking_spaces: 6,
    zone: MOCK_ZONES[4],
    title: "Mansión de altísima gama en Urbanización La Mara",
    short_description: "La joya de Mérida. Increíble mansión con piscina infinita climatizada, cine en casa, apartamento de huéspedes y jardines sublimes.",
    cover_image: {
      id: "prop-30-cover",
      property_id: "prop-30",
      url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80",
      alt_es: "Mansión de altísima gama en Urbanización La Mara",
      alt_en: "Mansión de altísima gama en Urbanización La Mara",
      sort_order: 0,
      is_cover: true,
    },
    images: [
      {
        id: "prop-30-img1",
        property_id: "prop-30",
        url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Mansión de altísima gama en Urbanización La Mara",
        alt_en: "Mansión de altísima gama en Urbanización La Mara",
        sort_order: 0,
        is_cover: true,
      },
      {
        id: "prop-30-img2",
        property_id: "prop-30",
        url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
        alt_es: "Mansión de altísima gama en Urbanización La Mara",
        alt_en: "Mansión de altísima gama en Urbanización La Mara",
        sort_order: 1,
        is_cover: false,
      }
    ],
  },
];

// ─── ESTADÍSTICAS PARA HERO ─────────────────────────────────
export const SITE_STATS = {
  propiedades: 47,
  zonas: 12,
  operaciones: 183,
  satisfaccion: 98,
};

// ─── TESTIMONIOS ────────────────────────────────────────────
export const MOCK_TESTIMONIALS = [
  {
    id: "t1",
    author_name: "Alejandro Mora",
    author_title: "Comprador — La Pedregosa",
    quote_es:
      "El proceso fue completamente diferente a todo lo que había vivido antes en Mérida. Claridad total, sin sorpresas, y encontraron exactamente lo que buscaba.",
    quote_en:
      "The process was completely different from anything I'd experienced before in Mérida. Total clarity, no surprises, and they found exactly what I was looking for.",
    rating: 5,
  },
  {
    id: "t2",
    author_name: "Valentina Torres",
    author_title: "Inversora — Las Tapias",
    quote_es:
      "Knordica entiende el mercado local a un nivel que ninguna otra firma aquí tiene. Su análisis fue lo que me convenció de invertir en Las Tapias.",
    quote_en:
      "Knordica understands the local market at a level no other firm here has. Their analysis was what convinced me to invest in Las Tapias.",
    rating: 5,
  },
  {
    id: "t3",
    author_name: "Roberto Sánchez",
    author_title: "Vendedor — El Encanto",
    quote_es:
      "Vendí en 6 semanas. La presentación digital que hicieron de mi propiedad fue de otro nivel. Todo en USD, sin complicaciones.",
    quote_en:
      "Sold in 6 weeks. The digital presentation they made of my property was on another level. Everything in USD, no complications.",
    rating: 5,
  },
];
