export const ZONAS_MERIDA = [
  { slug: "av-las-americas",      name_es: "Av. Las Américas",             name_en: "Las Américas Ave." },
  { slug: "av-urdaneta",          name_es: "Av. Urdaneta / Pie del Llano", name_en: "Urdaneta Ave." },
  { slug: "belen",                name_es: "Belén",                        name_en: "Belén" },
  { slug: "belensate",            name_es: "Belensate",                    name_en: "Belensate" },
  { slug: "campo-claro",          name_es: "Campo Claro",                  name_en: "Campo Claro" },
  { slug: "campo-de-oro",         name_es: "Campo de Oro",                 name_en: "Campo de Oro" },
  { slug: "casco-central",        name_es: "Casco Central",                name_en: "Downtown" },
  { slug: "cuenca-del-chama",     name_es: "Cuenca del Chama",             name_en: "Chama River Area" },
  { slug: "el-carrizal",          name_es: "El Carrizal",                  name_en: "El Carrizal" },
  { slug: "el-encanto",           name_es: "El Encanto",                   name_en: "El Encanto" },
  { slug: "el-valle-la-culata",   name_es: "El Valle / La Culata",         name_en: "El Valle" },
  { slug: "glorias-patrias",      name_es: "Glorias Patrias",              name_en: "Glorias Patrias" },
  { slug: "humboldt",             name_es: "Humboldt",                     name_en: "Humboldt" },
  { slug: "la-floresta",          name_es: "La Floresta",                  name_en: "La Floresta" },
  { slug: "la-hechicera",         name_es: "La Hechicera",                 name_en: "La Hechicera" },
  { slug: "la-hoyada-de-milla",   name_es: "La Hoyada de Milla",           name_en: "La Hoyada de Milla" },
  { slug: "la-mata",              name_es: "La Mata",                      name_en: "La Mata" },
  { slug: "la-milagrosa",         name_es: "La Milagrosa",                 name_en: "La Milagrosa" },
  { slug: "la-otra-banda",        name_es: "La Otra Banda",                name_en: "La Otra Banda" },
  { slug: "la-parroquia",         name_es: "La Parroquia",                 name_en: "La Parroquia" },
  { slug: "la-pedregosa",         name_es: "La Pedregosa",                 name_en: "La Pedregosa" },
  { slug: "la-pedregosa-alta",    name_es: "La Pedregosa Alta",            name_en: "La Pedregosa Alta" },
  { slug: "la-pedregosa-media",   name_es: "La Pedregosa Media",           name_en: "La Pedregosa Media" },
  { slug: "la-vuelta-mucujun",    name_es: "La Vuelta / Mucujún",          name_en: "La Vuelta / Mucujún" },
  { slug: "las-tapias",           name_es: "Las Tapias",                   name_en: "Las Tapias" },
  { slug: "los-chorros",          name_es: "Los Chorros de Milla",         name_en: "Los Chorros de Milla" },
  { slug: "los-curos",            name_es: "Los Curos",                    name_en: "Los Curos" },
  { slug: "milla",                name_es: "Milla",                        name_en: "Milla" },
  { slug: "pie-del-llano",        name_es: "Pie del Llano",                name_en: "Pie del Llano" },
  { slug: "san-jacinto",          name_es: "San Jacinto",                  name_en: "San Jacinto" },
  { slug: "santa-barbara",        name_es: "Santa Bárbara",                name_en: "Santa Bárbara" },
  { slug: "santa-elena",          name_es: "Santa Elena",                  name_en: "Santa Elena" },
  { slug: "santa-juana",          name_es: "Santa Juana",                  name_en: "Santa Juana" },
  { slug: "santa-rosa",           name_es: "Santa Rosa",                   name_en: "Santa Rosa" },
  { slug: "tabay",                name_es: "Tabay",                        name_en: "Tabay" },
  { slug: "zumba",                name_es: "Zumba",                        name_en: "Zumba" },
] as const;

export type ZonaSlug = typeof ZONAS_MERIDA[number]["slug"];
